CREATE TABLE "audit_logs" (
	"id" text PRIMARY KEY NOT NULL,
	"data_hora" text NOT NULL,
	"usuario_nome" text NOT NULL,
	"usuario_perfil" text NOT NULL,
	"acao" text NOT NULL,
	"entidade" text NOT NULL,
	"entidade_id" text NOT NULL,
	"detalhe" text NOT NULL,
	"ip" text NOT NULL,
	"browser" text,
	"alteracoes" jsonb
);
--> statement-breakpoint
CREATE TABLE "emprestimos" (
	"id" text PRIMARY KEY NOT NULL,
	"patrimonio_id" text NOT NULL,
	"codigo_patrimonial" text NOT NULL,
	"patrimonio_nome" text NOT NULL,
	"servidor_nome" text NOT NULL,
	"cpf_servidor" text,
	"cargo_servidor" text,
	"setor" text NOT NULL,
	"data_retirada" text NOT NULL,
	"previsao_devolucao" text NOT NULL,
	"data_devolucao" text,
	"status" text NOT NULL,
	"observacoes" text NOT NULL,
	"assinatura_digital_url" text,
	"assinatura_ip" text,
	"assinatura_data_hora" text,
	"termo_pdf_gerado" boolean
);
--> statement-breakpoint
CREATE TABLE "inventarios" (
	"id" text PRIMARY KEY NOT NULL,
	"titulo" text NOT NULL,
	"bloco" text NOT NULL,
	"laboratorio" text NOT NULL,
	"sala" text NOT NULL,
	"responsavel" text NOT NULL,
	"data_inicio" text NOT NULL,
	"data_fim" text,
	"total_esperados" integer NOT NULL,
	"total_encontrados" integer NOT NULL,
	"encontrados_ids" jsonb NOT NULL,
	"pendentes_ids" jsonb NOT NULL,
	"divergencias" jsonb,
	"status" text NOT NULL,
	"coordenadas_gps" jsonb
);
--> statement-breakpoint
CREATE TABLE "manutencoes" (
	"id" text PRIMARY KEY NOT NULL,
	"patrimonio_id" text NOT NULL,
	"codigo_patrimonial" text NOT NULL,
	"patrimonio_nome" text NOT NULL,
	"defeito" text NOT NULL,
	"prioridade" text NOT NULL,
	"tecnico_empresa" text NOT NULL,
	"custo" double precision NOT NULL,
	"data_abertura" text NOT NULL,
	"previsao_conclusao" text NOT NULL,
	"data_conclusao" text,
	"status" text NOT NULL,
	"laudo_tecnico" text NOT NULL,
	"garantia_servico_meses" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "patrimonios" (
	"id" text PRIMARY KEY NOT NULL,
	"codigo_patrimonial" text NOT NULL,
	"codigo_barras" text,
	"qr_code" text NOT NULL,
	"nome" text NOT NULL,
	"categoria" text NOT NULL,
	"marca" text NOT NULL,
	"modelo" text NOT NULL,
	"numero_serie" text NOT NULL,
	"fornecedor" text NOT NULL,
	"nota_fiscal" text NOT NULL,
	"data_aquisicao" text NOT NULL,
	"valor" double precision NOT NULL,
	"valor_residual" double precision,
	"taxa_depreciacao_anual" double precision,
	"garantia_vencimento" text NOT NULL,
	"vida_util_anos" integer NOT NULL,
	"estado_conservacao" text NOT NULL,
	"situacao" text NOT NULL,
	"bloco" text NOT NULL,
	"laboratorio" text NOT NULL,
	"sala" text NOT NULL,
	"setor" text,
	"centro_custo" text,
	"responsavel_nome" text NOT NULL,
	"responsavel_cpf" text NOT NULL,
	"observacoes" text NOT NULL,
	"foto_url" text NOT NULL,
	"fotos_adicionais" jsonb,
	"anexos_docs" jsonb,
	"data_cadastro" text NOT NULL,
	"ultima_atualizacao" text NOT NULL,
	CONSTRAINT "patrimonios_codigo_patrimonial_unique" UNIQUE("codigo_patrimonial"),
	CONSTRAINT "patrimonios_codigo_barras_unique" UNIQUE("codigo_barras")
);
