import { pgTable, text, timestamp, integer, doublePrecision, jsonb, boolean } from 'drizzle-orm/pg-core';

export const patrimonios = pgTable('patrimonios', {
  id: text('id').primaryKey(),
  codigoPatrimonial: text('codigo_patrimonial').notNull().unique(),
  codigoBarras: text('codigo_barras').unique(),
  qrCode: text('qr_code').notNull(),
  nome: text('nome').notNull(),
  categoria: text('categoria').notNull(),
  marca: text('marca').notNull(),
  modelo: text('modelo').notNull(),
  numeroSerie: text('numero_serie').notNull(),
  fornecedor: text('fornecedor').notNull(),
  notaFiscal: text('nota_fiscal').notNull(),
  dataAquisicao: text('data_aquisicao').notNull(),
  valor: doublePrecision('valor').notNull(),
  valorResidual: doublePrecision('valor_residual'),
  taxaDepreciacaoAnual: doublePrecision('taxa_depreciacao_anual'),
  garantiaVencimento: text('garantia_vencimento').notNull(),
  vidaUtilAnos: integer('vida_util_anos').notNull(),
  estadoConservacao: text('estado_conservacao').notNull(),
  situacao: text('situacao').notNull(),
  bloco: text('bloco').notNull(),
  laboratorio: text('laboratorio').notNull(),
  sala: text('sala').notNull(),
  setor: text('setor'),
  centroCusto: text('centro_custo'),
  responsavelNome: text('responsavel_nome').notNull(),
  responsavelCpf: text('responsavel_cpf').notNull(),
  observacoes: text('observacoes').notNull(),
  fotoUrl: text('foto_url').notNull(),
  fotosAdicionais: jsonb('fotos_adicionais'),
  anexosDocs: jsonb('anexos_docs'),
  dataCadastro: text('data_cadastro').notNull(),
  ultimaAtualizacao: text('ultima_atualizacao').notNull(),
});

export const emprestimos = pgTable('emprestimos', {
  id: text('id').primaryKey(),
  patrimonioId: text('patrimonio_id').notNull(),
  codigoPatrimonial: text('codigo_patrimonial').notNull(),
  patrimonioNome: text('patrimonio_nome').notNull(),
  servidorNome: text('servidor_nome').notNull(),
  cpfServidor: text('cpf_servidor'),
  cargoServidor: text('cargo_servidor'),
  setor: text('setor').notNull(),
  dataRetirada: text('data_retirada').notNull(),
  previsaoDevolucao: text('previsao_devolucao').notNull(),
  dataDevolucao: text('data_devolucao'),
  status: text('status').notNull(),
  observacoes: text('observacoes').notNull(),
  assinaturaDigitalUrl: text('assinatura_digital_url'),
  assinaturaIp: text('assinatura_ip'),
  assinaturaDataHora: text('assinatura_data_hora'),
  termoPdfGerado: boolean('termo_pdf_gerado'),
});

export const manutencoes = pgTable('manutencoes', {
  id: text('id').primaryKey(),
  patrimonioId: text('patrimonio_id').notNull(),
  codigoPatrimonial: text('codigo_patrimonial').notNull(),
  patrimonioNome: text('patrimonio_nome').notNull(),
  defeito: text('defeito').notNull(),
  prioridade: text('prioridade').notNull(),
  tecnicoEmpresa: text('tecnico_empresa').notNull(),
  custo: doublePrecision('custo').notNull(),
  dataAbertura: text('data_abertura').notNull(),
  previsaoConclusao: text('previsao_conclusao').notNull(),
  dataConclusao: text('data_conclusao'),
  status: text('status').notNull(),
  laudoTecnico: text('laudo_tecnico').notNull(),
  garantiaServicoMeses: integer('garantia_servico_meses').notNull(),
});

export const inventarios = pgTable('inventarios', {
  id: text('id').primaryKey(),
  titulo: text('titulo').notNull(),
  bloco: text('bloco').notNull(),
  laboratorio: text('laboratorio').notNull(),
  sala: text('sala').notNull(),
  responsavel: text('responsavel').notNull(),
  dataInicio: text('data_inicio').notNull(),
  dataFim: text('data_fim'),
  totalEsperados: integer('total_esperados').notNull(),
  totalEncontrados: integer('total_encontrados').notNull(),
  encontradosIds: jsonb('encontrados_ids').notNull(),
  pendentesIds: jsonb('pendentes_ids').notNull(),
  divergencias: jsonb('divergencias'),
  status: text('status').notNull(),
  coordenadasGps: jsonb('coordenadas_gps'),
});

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  login: text('login').notNull().unique(),
  nomeCompleto: text('nome_completo').notNull(),
  cpf: text('cpf').notNull(),
  matricula: text('matricula').notNull(),
  email: text('email').notNull().unique(),
  telefone: text('telefone'),
  cargo: text('cargo').notNull(),
  setor: text('setor').notNull(),
  role: text('role').notNull(),
  situacao: text('situacao').notNull(),
  passwordHash: text('password_hash').notNull(),
  forcePasswordChange: boolean('force_password_change').notNull(),
  tentativasInvalidas: integer('tentativas_invalidas').notNull().default(0),
  dataCriacao: text('data_criacao').notNull(),
  ultimoAcesso: text('ultimo_acesso'),
});

export const sectors = pgTable('sectors', {
  id: text('id').primaryKey(),
  nome: text('nome').notNull(),
  sigla: text('sigla').notNull(),
  responsavel: text('responsavel').notNull(),
  emailContact: text('email_contact'),
  totalPatrimonios: integer('total_patrimonios'),
});

export const movimentacoes = pgTable('movimentacoes', {
  id: text('id').primaryKey(),
  patrimonioId: text('patrimonio_id').notNull(),
  codigoPatrimonial: text('codigo_patrimonial').notNull(),
  patrimonioNome: text('patrimonio_nome').notNull(),
  dataHora: text('data_hora').notNull(),
  usuarioNome: text('usuario_nome').notNull(),
  usuarioPerfil: text('usuario_perfil').notNull(),
  localAnterior: text('local_anterior').notNull(),
  localNovo: text('local_novo').notNull(),
  responsavelAnterior: text('responsavel_anterior').notNull(),
  responsavelNovo: text('responsavel_novo').notNull(),
  motivo: text('motivo').notNull(),
  tipoOperacao: text('tipo_operacao').notNull(),
  dataRegistro: text('data_registro'),
});

export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  dataHora: text('data_hora').notNull(),
  usuarioNome: text('usuario_nome').notNull(),
  usuarioPerfil: text('usuario_perfil').notNull(),
  acao: text('acao').notNull(),
  entidade: text('entidade').notNull(),
  entidadeId: text('entidade_id').notNull(),
  detalhe: text('detalhe').notNull(),
  ip: text('ip').notNull(),
  browser: text('browser'),
  alteracoes: jsonb('alteracoes'),
});
